ignored_blocks = {
        "minecraft:air",
        "minecraft:stone_button",
        "minecraft:cobblestone_wall",
        "minecraft:smooth_stone_slab",
        "minecraft:stone_brick_slab",
        "minecraft:quartz_slab",
        "minecraft:iron_bars",
        "minecraft:iron_trapdoor",
        "minecraft:stone_brick_stairs",
        "minecraft:gray_carpet",
        "minecraft:red_carpet",
        "minecraft:light_blue_stained_glass",
        "minecraft:red_stained_pane",
        "minecraft:lever",
}